version: "3.8"

services:
  # Senin C# Core API Servisin
  blockchain-api:
    build:
      context: .
      dockerfile: BlockchainAPI/Dockerfile
    container_name: csharp_blockchain_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5008:8080"
    networks:
      - bmb_network

  # Emir'in Yapay Zeka Mikroservisi
  ai-service:
    build:
      context: ./AIMicroservice
      dockerfile: Dockerfile
    container_name: python_ai_service
    ports:
      - "5009:8000" # Emir'in servisi de 5009 portundan dışarı açılacak
    networks:
      - bmb_network

# İki servisin birbiriyle konuşabilmesi için özel bir köprü (network)
networks:
  bmb_network:
    driver: bridge
